blog/urls.py
from django.urls import re_path

from . import views

app_name = 'blog'

urlpatterns = [
    re_path(r'^$', views.IndexView.as_view(), name='index'),
    re_path(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    re_path(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    re_path(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    re_path(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    # re_path(r'^search/$', views.search, name='search')
    re_path(r'^search/$', views.SearchView.as_view(), name='search')
]

comments/urls.py
from django.urls import re_path
from . import views

app_name = 'comments'

urlpatterns = [
    re_path(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from blog.feeds import AllPostsRssFeed

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('comments.urls')),
    re_path(r'^all/rss/$', AllPostsRssFeed(), name='rss')
]

blog/models.py
import markdown
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.html import strip_tags


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()
    abstract = models.CharField(max_length=200, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    # page_view网页阅读量
    page_view = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ['-created_time']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        """ 实现自动摘要
            方法一：在被保存到数据库之前，从body自动摘取前50个字符，成为摘要abstract。
            方法二：在模板中使用过滤器{{ post.body|truncatechars:54 }}，不过如果有html标签，会比较难看。
        """
        if not self.abstract:
            # 实例化Markdown类，用于渲染body文本
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            # 将Markdown转换成HTML，然后去掉HTML文本的全部标签，从文本摘取前50个字符赋给abstract
            self.abstract = strip_tags(md.convert(self.body))[:50]

        super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def increase_page_view(self):
        self.page_view += 1
        self.save(update_fields=['page_view'])

comments/models.py
from django.db import models


# Create your models here.
class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    # Comment和Post是多对一关系
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE)

    def __str__(self):
        return self.text[:20]

blog/views.py
import markdown
from markdown.extensions.toc import TocExtension
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from django.utils.text import slugify
from django.db.models import Q

from comments.forms import CommentForm
from .models import Post, Category, Tag


class IndexView(ListView):
    # get_queryset()对Post进行操作。
    model = Post
    template_name = 'blog/index.html'
    # 就是get_queryset返回的数据保存到post_list中。
    context_object_name = 'post_list'
    # 如果在FBV中分页，要用到Django的Paginator。在CBV中，用属性
    paginate_by = 3

    def get_context_data(self, **kwargs):
        """完善分页功能(不再只有上一页，下一页)"""
        # 父类的context，是一个字典。
        context = super().get_context_data(**kwargs)
        paginator = context.get('paginator')
        # page是一个对象
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')

        # 调用自定义方法获取新增的context分页变量
        pagination_data = self.pagination_data(paginator, page, is_paginated)
        # 将新增的变量更新到context。此时context已有了显示分页导航条的数据。
        context.update(pagination_data)
        return context

    @staticmethod
    def pagination_data(paginator, page, is_paginated):
        if not is_paginated:
            # 如果没有分页，就没有必要return任何分页导航条的数据。
            return {}

        # 当前页要显示的左边、右边连续的页码
        left = []
        right = []
        # 表示第一页和最后一页是否需要显示省略号
        left_has_more = False
        right_has_more = False
        # 表示是否要显示第一页和最后一页
        first = False
        last = False

        # 当前页码
        page_number = page.number
        # 分页后的总页数
        total_pages = paginator.num_pages
        # 分页后的range
        page_range = paginator.page_range

        if page_number == 1:
            # 如果用户请求的是第一页, left默认为空。
            # 这里只获取当前页码后连续两个页码
            right = page_range[page_number:page_number + 2]

            if right[-1] < total_pages - 1:
                right_has_more = True

            if right[-1] < total_pages:
                last = True

        elif page_number == total_pages:
            # 如果用户请求的是最后一页，right默认为空。
            # 这里只获取当前页码前连续两个页码
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0: page_number - 1]

            # 如果最左边的页码比第二页页码大
            if left[0] > 2:
                left_has_more = True

            if left[0] > 1:
                first = True

        else:
            # 用户请求的是中间的页码
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0: page_number - 1]
            right = page_range[page_number:page_number + 2]

            # 是否需要显示最后一页和最后一页前的省略号
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True

            # 左边
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

            # context要更新的分页导航条的数据
        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }

        return data


# 简短写法
# @staticmethod
# def pagination_data(paginator, page, is_paginated):
#     if not is_paginated:
#         return {}
#     left = []
#     right = []
#     left_has_more = False
#     right_has_more = False
#     first = False
#     last = False
#
#     page_number = page.number
#     total_pages = paginator.num_pages
#     page_range = paginator.page_range
#
#     left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:
#                       (page_number - 1) if (page_number - 1) > 0 else 0]
#     right = page_range[page_number:page_number + 2]
#
#     if right:
#         if right[-1] < total_pages:
#             last = True
#         if right[-1] < total_pages - 1:
#             right_has_more = True
#     if left:
#         if left[0] > 1:
#             first = True
#         if left[0] > 2:
#             left_has_more = True
#
#     data = {'left': left,
#             'right': right,
#             'left_has_more': left_has_more,
#             'right_has_more': right_has_more,
#             'first': first,
#             'last': last, }
#
#     return data


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    # get_object, get_context_data都是辅助方法，都会在get中调用
    def get(self, request, *args, **kwargs):
        """get方法最终会返回一个HTTPResponse"""
        response = super().get(request, *args, **kwargs)

        # 文章阅读量+1。这里的object就是get_object()返回的object, 就是文章post的一个实例
        self.object.increase_page_view()

        return response

    def get_object(self, queryset=None):
        """覆写 get_object 方法的目的是因为需要对post的body值进行markdown渲染"""
        post = super().get_object(queryset=None)
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            # 'markdown.extensions.toc', 这个内置的拓展的锚点URL不美观(#_1，当有中文时就会简单的在#后加上_x)
            TocExtension(slugify=slugify)
        ])

        post.body = md.convert(post.body)
        post.toc = md.toc

        return post

    def get_context_data(self, **kwargs):
        """传递除context_object_name以外的变量到模板"""
        context = super().get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({
            'form': form,
            'comment_list': comment_list,
        })
        return context


class ArchivesView(IndexView):
    def get_queryset(self):
        # 在类视图中，从 URL 捕获的命名组参数值保存在实例的 kwargs 属性（是一个字典）里，非命名组参数值保存在实例的 args 属性（是一个元组）里。原理看ContextMixin。
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        return super().get_queryset().filter(created_time__year=year, created_time__month=month)


class CategoryView(IndexView):
    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        # 因为父类IndexView绑定了model = Post, 所以get_queryset对Post操作
        return super().get_queryset().filter(category=cate)


class TagView(IndexView):
    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super().get_queryset().filter(tags=tag)


# def search(request):
#     """简单的搜索功能"""
#     q = request.GET.get('q')
#     error_msg = ''
#
#     if not q:
#         error_msg = '请输入关键词'
#         return render(request, 'blog/index.html', {'error_msg': error_msg})
#
#     # Q提供了复杂的查询逻辑
#     post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))
#     return render(request, 'blog/index.html', {'error_msg': error_msg,
#                                                'post_list': post_list})

class SearchView(IndexView):
    def get(self, request, *args, **kwargs):
        """get方法最终会返回一个HTTPResponse"""
        q = request.GET.get('q')
        error_msg = ''

        if not q:
            error_msg = '请输入关键词'
            return render(request, 'blog/index.html', {'error_msg': error_msg})

        # Q提供了复杂的查询逻辑
        post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))
        return render(request, 'blog/index.html', {'error_msg': error_msg,
                                                   'post_list': post_list})

blog/templates/blog/base.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>Black &amp; White</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">

    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href={% url "blog:index" %}><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href={% url "blog:index" %} data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'blog:search' %}">
                            <input type="search" name="q" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-4">
                {% block toc %}
                {% endblock toc %}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_posts as recent_post_list %}
                    <ul>
                        {% for post in recent_post_list %}
                            <li>
                                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                            </li>
                        {% empty %}
                            暂无文章！
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                            <li>
                                <a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }}
                                    年 {{ date.month }} 月</a>
                            </li>
                        {% empty %}
                            暂无归档！
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                            <li>
                                <a href="{% url 'blog:category' category.pk %}">{{ category.name }} <span
                                        class="post-count">({{ category.num_posts }})</span></a>
                                <!-- post-count还可以category.post_set.count。-->
                            </li>
                        {% empty %}
                            暂无分类！
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    {% get_tags as tag_list %}
                    <ul>
                        {% for tag in tag_list %}
                            <li>
                                <a href="{% url 'blog:tag' tag.pk%}">{{ tag.name }}</a>
                            </li>
                        {% empty %}
                            暂无标签！
                        {% endfor %}
                    </ul>
                </div>


                <div class="rss">
                    <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'blog/js/script.js' %}"></script>

</body>
</html>

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block main %}
    <article class="post post-{{ post.pk }}">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                <span class="comments-link"><a href="#">{{ comment_list.count }}</a></span>
                <span class="views-count"><a href="#">{{ post.page_view }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ post.body|safe }}
            <div class="widget widget-tag-cloud">
                <ul>
                    标签：
                    <!-- Post中的tags，是多对多关系，用post.tags访问会返回一个模型管理器 -->
                    {% for tag in post.tags.all %}
                        <li><a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </article>
    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
        <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4">
                    <label for="{{ form.name.id_for_label }}">名字：</label>
                    {{ form.name }}
                    {{ form.name.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.email.id_for_label }}">邮箱：</label>
                    {{ form.email }}
                    {{ form.email.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.url.id_for_label }}">URL：</label>
                    {{ form.url }}
                    {{ form.url.errors }}
                </div>
                <div class="col-md-12">
                    <label for="{{ form.text.id_for_label }}">评论：</label>
                    {{ form.text }}
                    {{ form.text.errors }}
                    <button type="submit" class="comment-btn">发表</button>
                </div>
            </div>    <!-- row -->
        </form>
        <div class="comment-list-panel">
            <h3>评论列表，共 <span>{{ comment_list.count }}</span> 条评论</h3>
            <ul class="comment-list list-unstyled">
                {% for comment in comment_list %}
                    <li class="comment-item">
                        <span class="nickname">{{ comment.name }}</span>
                        <time class="submit-date"
                              datetime="{{ comment.created_time }}">{{ comment.created_time }}</time>
                        <div class="text">
                            {{ comment.text }}
                        </div>
                    </li>
                {% empty %}
                    暂无评论
                {% endfor %}
            </ul>
        </div>
    </section>
{% endblock main %}

{% block toc %}
    <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
        {{ post.toc | safe }}
    </div>
{% endblock toc %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block main %}
    {% if error_msg %}
        <h1 style="color:red">{{ error_msg }}</h1>
    {% endif %}
    {% for post in post_list %}
        <article class="post post-{{ post.pk }}">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                              datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                    <span class="post-author"><a href="#">{{ post.author }}</a></span>
                    <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
                    <span class="views-count"><a href="#">{{ post.page_view }} 阅读</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{ post.abstract }}</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
    {% empty %}
        <div class="no-post">暂时还没有发布的文章！</div>
    {% endfor %}

    <!-- 分页, 基于CBV，穿过来的context有Paginator自带的4个加上自定义的6个变量。详细看IndexView的get_context_data -->
    {% if is_paginated %}
    <div class="pagination">
        <!-- 第一页 -->
        {% if first %}
            <a href="?page=1">1</a>
        {% endif %}
        <!-- 当前页的左边 -->
        {% if left %}
            {% if left_has_more %}
                <span>...</span>
            {% endif %}
            {% for page_num in left %}
                <a href="?page={{ page_num }}">{{ page_num }}</a>
            {% endfor %}
        {% endif %}
        <!-- 当前页-->
        <a href="?page={{ page_obj.number }}" style="color: #44B78B">{{ page_obj.number }}</a>
        <!-- 当前页的右边 -->
        {% if right %}
            {% if right_has_more %}
                <span>...</span>
            {% endif %}
            {% for page_num in right %}
                <a href="?page={{ page_num }}">{{ page_num }}</a>
            {% endfor %}
        {% endif %}
        <!-- 最后一页 -->
        {% if last %}
            <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
        {% endif %}

    </div>
    {% endif %}

{% endblock main %}